import type { Metadata } from "next";
import localFont from "next/font/local";

import "@/styles/globals.css";
import styles from "@/app/style.module.scss";
import Head from "next/head";
import Image from "next/image";

const hms = localFont({
  src: [
    {
      path: "./fonts/HarmonyOS_Sans/HarmonyOS_Sans_Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans/HarmonyOS_Sans_Regular.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans/HarmonyOS_Sans_Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans/HarmonyOS_Sans_Bold.ttf",
      weight: "700",
      style: "normal",
    },
    {
      path: "./fonts/HarmonyOS_Sans/HarmonyOS_Sans_Black.ttf",
      weight: "900",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "PAYHUB",
  // description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <Head>
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <body>
        {/* <main className="flex w-full min-h-screen flex-col items-center justify-center mx-auto"> */}
          {/* <div className="flex flex-col w-full max-w-full h-screen sm:h-auto sm:w-[495px] sm:rounded-3xl main"> */}
            {/* <Image src={"/images/header.svg"} alt={""} width={129} height={55} className="w-full sm:rounded-t-3xl" /> */}
            <div className={styles.content}>{children}</div>
          {/* </div> */}
        {/* </main> */}
      </body>
    </html>
  );
}
